const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';

const GET_FRIENDS_LIST = 'GET_FRIENDS_LIST';
const SELECT_THIS_FRIEND = 'SELECT_THIS_FRIEND';
const USE_THIS_AVATAR = 'USE_THIS_AVATAR';
